### ISSUE TITLE
Logically disconnect/reconnect from the charger

### ISSUE THREAD

**Issue by Stevenejones** [lendy007/skodaconnect#128]
Sorry new at this. 
Request the ability to logically disconnect and reconnect to the charger so that the charger believes that the car has just been plugged in. 
Reason is that with tariffs like the octopus agile tariff the rate for the following morning (post midnight till 7am) is not known until late afternoon, the behaviour of the charging companies seems to be that upon plugging in they workout the charging schedule, which if this is done before tomorrow's price profile is released causes the charging profile to fill up the last slots of the current day which is all that it knows about at this time. 
By forcing the charger to think that the car has been plugged in again it would recalculate the charging slots, I'd intend to set an automation in home assistant to reset this atsay 10pm. 
I don't believe that this is covered by existing functionality, and to be clear I do not know if this is possible.

**Comment by WebSpider** [comment]
I understand your request, and have run into this myself as well with some chargers.

Most public chargers detect the presence of a car initially because the cable is inserted, which is a physical trigger.

Are you aware of any car or software that can make the charger you are referring to think they have reconnected?

**Comment by Stevenejones** [comment]
No, this is for my home charger, i've checked with them and they have no such functionality. I fully accept that it may not be possible, it would allow abuse of the free 15mins on some pubic chargers for instance. I'm just going to have to plug in after octopus release their morning rates unti Indra/Kaluza fix it.
