### ISSUE TITLE
Error when Execute Example.py

### ISSUE THREAD

**Issue by heckmic** [lendy007/skodaconnect#14]
This is what i get:

python3 example.py

DEBUG:asyncio:Using selector: EpollSelector
Initiating new session to Skoda Connect with michael27983@gmail.com as username
DEBUG:skodaconnect.connection:Using service https://msg.volkswagen.de
Attempting to login to the Skoda Connect service
Traceback (most recent call last):
  File "example.py", line 205, in <module>
    loop.run_until_complete(main())
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "example.py", line 101, in main
    if await connection.doLogin():
AttributeError: 'Connection' object has no attribute 'doLogin'

I only filled in my credentials and thought there should be a result.

**Comment by Farfar** [comment]
It should work right off the bat. Do you have an old skodaconnect version installed? Since it doesn't throw an error in import then I suspect that it might load incorrect library version.

If the library isn't installed then you can try running from the parent directory, it might be a problem with path.

**Comment by mcluki** [comment]
Same here (on a fresh installation):

Successfully installed beautifulsoup4-4.9.3 iniconfig-1.1.1 lxml-4.6.3 pluggy-0.13.1 py-1.10.0 pyjwt-1.7.1 pytest-6.2.4 pytest-asyncio-0.15.1 skodaconnect-1.0.37 soupsieve-2.2.1

[skodaconnect]$ cd example/
[example]$ python example.py 
DEBUG:asyncio:Using selector: EpollSelector
Initiating new session to Skoda Connect with xxxxxxx@yyy as username
DEBUG:skodaconnect.connection:Using service https://msg.volkswagen.de
Attempting to login to the Skoda Connect service
Traceback (most recent call last):
  File "/home/abcDocuments/DEV/skodaconnect/example/example.py", line 205, in <module>
    loop.run_until_complete(main())
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/abc/Documents/DEV/skodaconnect/example/example.py", line 101, in main
    if await connection.doLogin():
AttributeError: 'Connection' object has no attribute 'doLogin'

**Comment by Farfar** [comment]
> Same here (on a fresh installation):
> 
> Successfully installed beautifulsoup4-4.9.3 iniconfig-1.1.1 lxml-4.6.3 pluggy-0.13.1 py-1.10.0 pyjwt-1.7.1 pytest-6.2.4 pytest-asyncio-0.15.1 skodaconnect-1.0.37 soupsieve-2.2.1
> 
> [skodaconnect]$ cd example/
> [example]$ python example.py
> DEBUG:asyncio:Using selector: EpollSelector
> Initiating new session to Skoda Connect with xxxxxxx@yyy as username
> DEBUG:skodaconnect.connection:Using service https://msg.volkswagen.de
> Attempting to login to the Skoda Connect service
> Traceback (most recent call last):
> File "/home/abcDocuments/DEV/skodaconnect/example/example.py", line 205, in
> loop.run_until_complete(main())
> File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
> return future.result()
> File "/home/abc/Documents/DEV/skodaconnect/example/example.py", line 101, in main
> if await connection.doLogin():
> AttributeError: 'Connection' object has no attribute 'doLogin'

Ah then I understand. It's an issue with relative import, try running the code from the librarys base directory instead. The parent directory from example.py.
I will fix for next commit.

**Comment by Farfar** [comment]
Fixed in latest commit.
