### ISSUE TITLE
TypeError: getRealCarData() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by javierin** [lendy007/skodaconnect#15]
I am finding some trouble after the initial data fetch with an Enyaq, which results in the following output

```
########## 09:54:23 AM - NEW LOOP ##########
TMBJC7NY1MFxxxxxx Charging time left - (charging_time_left)
	str_state: 0 h - state: 0
	attributes: {}

TMBJC7NY1MFxxxxxx Electric range - (electric_range)
	str_state: 344 km - state: 344
	attributes: {}

TMBJC7NY1MFxxxxxx Battery level - (battery_level)
	str_state: 78 % - state: 78
	attributes: {}

TMBJC7NY1MFxxxxxx External power - (external_power)
	str_state: On - state: True
	attributes: {}

TMBJC7NY1MFxxxxxx Charging cable connected - (charging_cable_connected)
	str_state: Charging - state: True
	attributes: {}

TMBJC7NY1MFxxxxxx Charging - (charging)
	str_state: Off - state: 0
	attributes: {'last_result': ''}

TMBJC7NY1MFxxxxxx Charging cable locked - (charging_cable_locked)
	str_state: Locked - state: None
	attributes: {}

Sleeping for 20 seconds
Updating ALL values from Skoda Connect...
Success!
Updating INDIVIDUAL values for TMBJC7NY1MFxxxxxx...
Updating carportdata...
Updating charger data...
Updating climater data...
Updating position data...
Updating pre-heater data...
Updating realcardata...
Traceback (most recent call last):
  File "skoda.py", line 315, in <module>
    loop.run_until_complete(main())
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "skoda.py", line 285, in main
    await vehicle.get_realcardata()
  File "xxxxxxx/skodaconnect/vehicle.py", line 154, in get_realcardata
    data = await self._connection.getRealCarData(self.vin)
TypeError: getRealCarData() takes 1 positional argument but 2 were given
```

**Comment by Farfar** [comment]
> Updating realcardata...
> Traceback (most recent call last):
>   File "skoda.py", line 315, in <module>
>     loop.run_until_complete(main())
>   File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
>     return future.result()
>   File "skoda.py", line 285, in main
>     await vehicle.get_realcardata()
>   File "xxxxxxx/skodaconnect/vehicle.py", line 154, in get_realcardata
>     data = await self._connection.getRealCarData(self.vin)
> TypeError: getRealCarData() takes 1 positional argument but 2 were given

Thanks, I'll fix this in next commit.

**Comment by javierin** [comment]
Thanks @Farfar This fix resulted in the following error:

```
Sleeping for 20 seconds
Updating ALL values from Skoda Connect...
Success!
Updating INDIVIDUAL values for TMBJC7NY1MFxxxxxx...
Updating carportdata...
Updating charger data...
Updating climater data...
Updating position data...
Updating pre-heater data...
Updating realcardata...
Traceback (most recent call last):
  File "skoda.py", line 315, in <module>
    loop.run_until_complete(main())
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "skoda.py", line 285, in main
    await vehicle.get_realcardata()
  File "xxxxxx/skodaconnect/vehicle.py", line 156, in get_realcardata
    self._states.update(data)
ValueError: dictionary update sequence element #0 has length 7; 2 is required
```

Best regards

**Comment by Farfar** [comment]
> Thanks @Farfar This fix resulted in the following error:
> 
> ```
> Sleeping for 20 seconds
> Updating ALL values from Skoda Connect...
> Success!
> Updating INDIVIDUAL values for TMBJC7NY1MFxxxxxx...
> Updating carportdata...
> Updating charger data...
> Updating climater data...
> Updating position data...
> Updating pre-heater data...
> Updating realcardata...
> Traceback (most recent call last):
>   File "skoda.py", line 315, in <module>
>     loop.run_until_complete(main())
>   File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
>     return future.result()
>   File "skoda.py", line 285, in main
>     await vehicle.get_realcardata()
>   File "xxxxxx/skodaconnect/vehicle.py", line 156, in get_realcardata
>     self._states.update(data)
> ValueError: dictionary update sequence element #0 has length 7; 2 is required
> ```
> 
> Best regards

Seems like it's more places in example code that the changes have broken stuff. I will look through once more.

**Comment by Farfar** [comment]
Fixed in latest commit and release 1.0.46rc6

**Comment by javierin** [comment]
Hi @Farfar 

Now we have a different issue, looks like it triggers before the others

```
Sleeping for 20 seconds
Updating ALL values from Skoda Connect...
Success!
Updating INDIVIDUAL values for TMBJC7NY1MFxxxxxx...
Updating carportdata...
Traceback (most recent call last):
  File "skoda.py", line 315, in <module>
    loop.run_until_complete(main())
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "skoda.py", line 275, in main
    await vehicle.get_carportdata()
AttributeError: 'Vehicle' object has no attribute 'get_carportdata'
```


Kind regards

**Comment by Farfar** [comment]
> Hi @Farfar
> 
> Now we have a different issue, looks like it triggers before the others
> 
> ```
> Sleeping for 20 seconds
> Updating ALL values from Skoda Connect...
> Success!
> Updating INDIVIDUAL values for TMBJC7NY1MFxxxxxx...
> Updating carportdata...
> Traceback (most recent call last):
>   File "skoda.py", line 315, in <module>
>     loop.run_until_complete(main())
>   File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
>     return future.result()
>   File "skoda.py", line 275, in main
>     await vehicle.get_carportdata()
> AttributeError: 'Vehicle' object has no attribute 'get_carportdata'
> ```
> 
> Kind regards

Make sure you are using latest example code and library.
The carportdata function has been removed since Skoda has migrated the information to new API endpoints.

**Comment by javierin** [comment]
Absolutely agree with your point. I did not update the code in my script. 

I did a brand new git clone to a new directory but got similar results:

```
########################################
#    Updating all values from Skoda    #
########################################
Updating ALL values from Skoda Connect...
DEBUG:skodaconnect.connection:Going to call vehicle updates
DEBUG:skodaconnect.connection:Adding TMBJC7NY1MFxxxxxx for data refresh
DEBUG:skodaconnect.connection:Calling update function for all vehicles
DEBUG:skodaconnect.connection:HTTP GET "https://api.connect.skoda-auto.cz/api/v1/charging/TMBJC7NY1MFxxxxxx/status"
DEBUG:skodaconnect.connection:Request for "https://api.connect.skoda-auto.cz/api/v1/charging/TMBJC7NY1MFxxxxxx/status" returned with status code [200], response: {'plug': {'connectionState': 'Connected', 'lockState': 'Locked'}, 'charging': {'state': 'ReadyForCharging', 'remainingToCompleteInSeconds': 0, 'chargingPowerInWatts': 4000.0, 'chargingRateInKilometersPerHour': 0.0, 'chargingType': 'Invalid', 'chargeMode': 'OFF'}, 'battery': {'cruisingRangeElectricInMeters': 304000, 'stateOfChargeInPercent': 66}}
DEBUG:skodaconnect.connection:Got vehicle data {'plug': {'connectionState': 'Connected', 'lockState': 'Locked'}, 'charging': {'state': 'ReadyForCharging', 'remainingToCompleteInSeconds': 0, 'chargingPowerInWatts': 4000.0, 'chargingRateInKilometersPerHour': 0.0, 'chargingType': 'Invalid', 'chargeMode': 'OFF'}, 'battery': {'cruisingRangeElectricInMeters': 304000, 'stateOfChargeInPercent': 66}}
Success!

Sleeping for 20 seconds

########################################
#          Update carportdata          #
###########TMBJC7NY1MFxxxxxx############
Traceback (most recent call last):
  File "example.py", line 282, in <module>
    loop.run_until_complete(main())
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "example.py", line 206, in main
    await vehicle.get_carportdata()
AttributeError: 'Vehicle' object has no attribute 'get_carportdata'
```

**Comment by Farfar** [comment]
> Absolutely agree with your point. I did not update the code in my script.
> 
> I did a brand new git clone to a new directory but got similar results:
> 
> ```
> ########################################
> #    Updating all values from Skoda    #
> ########################################
> Updating ALL values from Skoda Connect...
> DEBUG:skodaconnect.connection:Going to call vehicle updates
> DEBUG:skodaconnect.connection:Adding TMBJC7NY1MFxxxxxx for data refresh
> DEBUG:skodaconnect.connection:Calling update function for all vehicles
> DEBUG:skodaconnect.connection:HTTP GET "https://api.connect.skoda-auto.cz/api/v1/charging/TMBJC7NY1MFxxxxxx/status"
> DEBUG:skodaconnect.connection:Request for "https://api.connect.skoda-auto.cz/api/v1/charging/TMBJC7NY1MFxxxxxx/status" returned with status code [200], response: {'plug': {'connectionState': 'Connected', 'lockState': 'Locked'}, 'charging': {'state': 'ReadyForCharging', 'remainingToCompleteInSeconds': 0, 'chargingPowerInWatts': 4000.0, 'chargingRateInKilometersPerHour': 0.0, 'chargingType': 'Invalid', 'chargeMode': 'OFF'}, 'battery': {'cruisingRangeElectricInMeters': 304000, 'stateOfChargeInPercent': 66}}
> DEBUG:skodaconnect.connection:Got vehicle data {'plug': {'connectionState': 'Connected', 'lockState': 'Locked'}, 'charging': {'state': 'ReadyForCharging', 'remainingToCompleteInSeconds': 0, 'chargingPowerInWatts': 4000.0, 'chargingRateInKilometersPerHour': 0.0, 'chargingType': 'Invalid', 'chargeMode': 'OFF'}, 'battery': {'cruisingRangeElectricInMeters': 304000, 'stateOfChargeInPercent': 66}}
> Success!
> 
> Sleeping for 20 seconds
> 
> ########################################
> #          Update carportdata          #
> ###########TMBJC7NY1MFxxxxxx############
> Traceback (most recent call last):
>   File "example.py", line 282, in <module>
>     loop.run_until_complete(main())
>   File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
>     return future.result()
>   File "example.py", line 206, in main
>     await vehicle.get_carportdata()
> AttributeError: 'Vehicle' object has no attribute 'get_carportdata'
> ```

That's my bad. I forgot to actually remove the lines from the example. You can remove lines 202-206 or pull latest commit.

**Comment by javierin** [comment]
Now it is working just fine. Thanks!
