### ISSUE TITLE
Charging cable locked showing wrong data

### ISSUE THREAD

**Issue by flopp999** [lendy007/skodaconnect#17]
`Request for "https://api.connect.skoda-auto.cz/api/v1/charging/TMBXXXXXX/status" returned with status code [200], response: {'plug': {'connectionState': 'Connected', 'lockState': 'Unlocked'}`

`DEBUG:skodaconnect.connection:Got vehicle data {'plug': {'connectionState': 'Connected', 'lockState': 'Unlocked'}`

TMBJXxxxxxxxxxxxx Charging cable locked - (charging_cable_locked)
        str_state: Locked - state: None
        attributes: {}

https://github.com/lendy007/skodaconnect/blob/d86ce730199fdb66ec91c01cfc38b0ce094477ee/skodaconnect/dashboard.py#L145

https://github.com/lendy007/skodaconnect/blob/6525f3d112cb8be52dc190a72fc039de389b7801/skodaconnect/vehicle.py#L1037

**Comment by Farfar** [comment]
Should be fixed in 1.0.42
