### ISSUE TITLE
I own a Skoda Enyaq

### ISSUE THREAD

**Issue by flopp999** [lendy007/skodaconnect#21]
I can get some charging data but not so much more, since Skoda has not make all available.

When I run example.py I do get some data that might help you to develop this script.

`DEBUG:skodaconnect.vehicle:Creating Vehicle class object with data {'vin': 'xxxxxxxxxxxxxxxx', 'connectivities': ['REMOTE'], 'capabilities': ['DCS', 'AUTOMATION', 'CHARGING', 'CHARGING_STATIONS', 'AIR_CONDITIONING', 'DESTINATIONS', 'FUEL_STATUS', 'MAP_UPDATE', 'ONLINE_SPEECH', 'PARKING_INFORMATION', 'ROUTING', 'TRAFFIC_INFORMATION', 'WEB_RADIO'], 'specification': {'title': 'ŠKODA ENYAQ iV', 'brand': 'ŠKODA', 'model': 'ENYAQ iV', 'body': 'SUV', 'systemCode': 'ENYAQ iV       60         132/62   E1H', 'systemModelId': '5AZFF2', 'engine': {'type': 'iV', 'powerInKW': 132}, 'battery': {'capacityInKWh': 62}, 'gearbox': {'type': 'E1H'}, 'trimLevel': '60', 'manufacturingDate': '2021-mm-dd', 'devicePlatform': 'WCAR', 'maxChargingPowerInKW': 100}, 'nickname': None, 'deactivated': False}
`

Is this something that you can use?

My thought is that you use CHARGING in here https://github.com/lendy007/skodaconnect/blob/37a7dd905ca9416ee3508b435b671ccaced59bf1/skodaconnect/vehicle.py#L80.
so maybe it possible to add all above from capabilities, like DCS, FUEL_STATUS etc?

**Comment by Farfar** [comment]
Well yes and no. I already have a bit of data from Enyaq debugs and I have made available what I can and have found as of 1 month ago. But maybe there's an option to start and stop charging now? I will take a look.



> My thought is that you use CHARGING in here

That line is only used to prepare dictionaries for what kind of capabilities the car has. That it says "False" is only a placeholder,  it's enabled later in the discovery phase if the API endpoint actually works.

**Comment by flopp999** [comment]
Nice, then I will wait for the new version and see what I can collect.

Thanks

**Comment by flopp999** [comment]
I updated to 1.0.42, that was quickly done :)

I tried the example but I couldn't see any new data, charger-data is there.

Have I done something wrong or there will be more data when Skoda opens it?

**Comment by Farfar** [comment]
> I updated to 1.0.42, that was quickly done :)
> 
> I tried the example but I couldn't see any new data, charger-data is there.
> 
> Have I done something wrong or there will be more data when Skoda opens it?

First Skoda needs to add new data and functionality to the API. Then I need to add it to the code.
The latest release should have fixes for many small issues but no new functionality for Enyaq. I will investigate and see if Skoda has added something new but a month ago they hadn't.

**Comment by flopp999** [comment]
Thank you

Do you have any buymeacoffee-link or can I donate to you in other way.

Your work is great
