### ISSUE TITLE
activate DEBUG

### ISSUE THREAD

**Issue by flopp999** [lendy007/skodaconnect#22]
I am using skodaconnect in my own python script.

After ~9 hours it fails.

Where can I find log files and how can I activate DEBUG mode?

**Comment by Farfar** [comment]
> I am using skodaconnect in my own python script.
> 
> After ~9 hours it fails.
> 
> Where can I find log files and how can I activate DEBUG mode?

It's using the logging module and will use whatever log settings you set it up with.
