### ISSUE TITLE
Škoda Enyaq - start / stop for charge does not work

### ISSUE THREAD

**Issue by wieshka** [lendy007/skodaconnect#24]
Hi @lendy007, thanks for this package,

Trying to figure out why start/stop commands are not working on my Enyaq, and wanted to ask what's the status around this functionality from your side?

At the same time, in MyŠkoda app, which, I assume, uses the very same API, start/stop buttons for charging are working.

Eager to help, just let me know how can I help.

**Comment by wieshka** [comment]
Update: tried to intercept (MITM) official Skoda application (MySkoda) requests regarding setting charger state - no luck - the app has checks in place for man-in-the-middle. Not that I am surprised, but at least I tried since I can't find what API end-points with what payloads should be used. 

Any other tips for reverse engineering?

**Comment by Farfar** [comment]
> Update: tried to intercept (MITM) official Skoda application (MySkoda) requests regarding setting charger state - no luck - the app has checks in place for man-in-the-middle. Not that I am surprised, but at least I tried since I can't find what API end-points with what payloads should be used.
> 
> Any other tips for reverse engineering?
> 
> Perhaps it's worth taking some old iPhone I have around and jailbrake it for wider reverse engineering options?

I will look into this as soon as I have the time for it. Right now it's not until the end of August.

If you want to reverse engineer you can look att Frida and Objection and see if you can reverse the SSL pinning of the app so you can use MITM proxy.

**Comment by wieshka** [comment]
Thank you @Farfar for tips - with quite a bit of trial & error, mostly due to lack of experience with jailbreak, managed to get API endpoints and payloads, and dropping them here as getting to implementation might take me a while:


**Start charging:**
POST to `/api/v1/charging/operation-requests?vin=<VIN>` with payload:
```
{
  "type": "Start"
}
```

**Stop charging:**
POST to `/api/v1/charging/operation-requests?vin=<VIN>` with payload:
```
{
  "type": "Stop"
}
```

**Expected response:**
```
{
  "id": "<unique-request-id>",
  "status": "<status>"
```
Where status seems to be either InProgress & Completed when done.

Request status can be checked with GET against `/api/v1/charging/operation-requests/<unique-request-id>`

**Comment by Farfar** [comment]
> Thank you @Farfar for tips - with quite a bit of trial & error, mostly due to lack of experience with jailbreak, managed to get API endpoints and payloads, and dropping them here as getting to implementation might take me a while:
> 
> **Start charging:**
> POST to `/api/v1/charging/operation-requests?vin=<VIN>` with payload:
> 
> ```
> {
>   "type": "Start"
> }
> ```
> 
> **Stop charging:**
> POST to `/api/v1/charging/operation-requests?vin=<VIN>` with payload:
> 
> ```
> {
>   "type": "Stop"
> }
> ```
> 
> **Set charge limit/settings**
> POST to `/api/v1/charging/operation-requests?vin=<VIN>` with payload:
> 
> ```
> {
> 	"type": "UpdateSettings",
> 	"chargingSettings": {
> 		"targetStateOfChargeInPercent": 90,
> 		"maxChargeCurrentAc": "Maximum",
> 		"autoUnlockPlugWhenCharged": "Off"
> 	}
> }
> ```
> 
> **Expected response:**
> 
> ```
> {
>   "id": "<unique-request-id>",
>   "status": "<status>"
> ```
> 
> Where status seems to be either InProgress & Completed when done.
> 
> Request status can be checked with GET against `/api/v1/charging/operation-requests/<unique-request-id>`

Thanks, it looks quite similar to the VW API requests so Will probably be easy to implement. Without checking the code it should be enough to just use the different API endpoints and perhaps tweak some formatting of the data.

**Comment by wieshka** [comment]
I attempted to wrap my head around this and make my own attempt to implement it, but it's too specific and I am not getting anywhere with it, so I suppose I will have to leave this for more experienced devs to pick up. 

Other than that, consider you have me to a) do any additional reverse-engineering if needed, b) somebody to test this on actual Enyaq. 

Let me know if we can move to a faster medium, perhaps some Slack or IRC channel, etc for immediate help from my side when needed.

**Comment by Farfar** [comment]
I mostly use Discord and just created a server for this purpose. You can join if you wish but it's only me so far.

-BR

Hämta Outlook för Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by Farfar** [comment]
Also helps if I post a link :D
https://discord.gg/qYcqEaxV

-BR

Hämta Outlook för Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by wieshka** [comment]
Dirty patch of #25 tested on my Enyaq - works as expected. Mind that I clearly introduced breaking changes for older cars, so, nicer wrapping by maintainers is required to support both old and new APIs. 

Once I would see normalized implementation of this most wanted functionality, happy to try to implement other available commands by following the example established around this one. Or at least, produce similar dirty patches as I am still drowning in the rest of the code base.

**Comment by Farfar** [comment]
This should be working with latest commit, version 1.0.43.
