### ISSUE TITLE
Feature request: Honk and Flash

### ISSUE THREAD

**Issue by dominikkarall** [lendy007/skodaconnect#28]
Would be great if honk_and_flash could be supported as well.

See iobroker adapter for details:
https://github.com/TA2k/ioBroker.vw-connect/blob/43a48b9443bea971e65d14f33e5766be2156b03f/main.js#L3599

Thanks!

**Comment by Farfar** [comment]
I can make it work for an upcoming release. I had it in planning but never really use it so never came around to implementing it. Should be quick fix as soon as I have time to work on it.

**Comment by Farfar** [comment]
Added in commit https://github.com/lendy007/skodaconnect/commit/31c6878257b9723133f16fd3a4aaf199a3b1dfb2#diff-d71651901ee84eed15f18f518e8cb094b33c8d536f3844ba7014273239e47ded, will be included in release 1.1.0 when I make it available.
