### ISSUE TITLE
Login issue with Skoda CityGo

### ISSUE THREAD

**Issue by andig** [lendy007/skodaconnect#31]
This is what the debug log shows for current master:

    DEBUG:skodaconnect.connection:Failed to verify connect token, error: module 'jwt.algorithms' has no attribute 'RSAAlgorithm'
    DEBUG:skodaconnect.connection:The Connect services token is invalid
    ERROR:skodaconnect.connection:Failed to fetch VW-Group API tokens, Invalid connect token

**Comment by Farfar** [comment]
Looks like you have the wrong version of pyjwt. Make sure you are using pyjwt==1.7.1 as stated in requirements.

**Comment by andig** [comment]
Same thing after doing:

```
❯ pip3 install pyjwt==1.7.1
Collecting pyjwt==1.7.1
  Using cached PyJWT-1.7.1-py2.py3-none-any.whl (18 kB)
Installing collected packages: pyjwt
  Attempting uninstall: pyjwt
    Found existing installation: PyJWT 2.1.0
    Uninstalling PyJWT-2.1.0:
      Successfully uninstalled PyJWT-2.1.0
Successfully installed pyjwt-1.7.1
WARNING: You are using pip version 21.1.3; however, version 21.2.4 is available.
You should consider upgrading via the '/opt/homebrew/opt/python@3.9/bin/python3.9 -m pip install --upgrade pip' command.
```

**Comment by Farfar** [comment]
You might need to install the cryptography module as well. I will add it as a dependency

**Comment by andig** [comment]
Check. `pywt[crypto]` does the trick.
