### ISSUE TITLE
Phyton Error

### ISSUE THREAD

**Issue by hhoefling** [lendy007/skodaconnect#34]
Hello i try to use these code with Phyton3.9

at  "Departure timer 1 departure1 " 
-->
Traceback (most recent call last):
  File "/var/www/html/callskoda.py", line 240, in <module>
    loop.run_until_complete(main())
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/var/www/html/callskoda.py", line 204, in main
    print(f'{instrument.full_name} {instrument.attr}  - ({val})\tstr_state: ({instrument.str_state})\tattributes: {instrument.attributes}')
  File "/var/www/html/skodaconnect/dashboard.py", line 295, in str_state
    str(datetime.strptime(ts,'%Y-%m-%dT%H:%M:%SZ').astimezone(tz=None)) if ts else None,
TypeError: strptime() argument 1 must be str, not datetime.datetime

any Idee?
with python Version are used?

lg
Heinz

**Comment by Farfar** [comment]
> Hello i try to use these code with Phyton3.9
> 
> at "Departure timer 1 departure1 "
> -->
> Traceback (most recent call last):
> File "/var/www/html/callskoda.py", line 240, in
> loop.run_until_complete(main())
> File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
> return future.result()
> File "/var/www/html/callskoda.py", line 204, in main
> print(f'{instrument.full_name} {instrument.attr} - ({val})\tstr_state: ({instrument.str_state})\tattributes: {instrument.attributes}')
> File "/var/www/html/skodaconnect/dashboard.py", line 295, in str_state
> str(datetime.strptime(ts,'%Y-%m-%dT%H:%M:%SZ').astimezone(tz=None)) if ts else None,
> TypeError: strptime() argument 1 must be str, not datetime.datetime
> 
> any Idee?
> with python Version are used?
> 
> lg
> Heinz

Hi,

Should work with versions 3.7-3.9 but I haven't tested 3.9 myself.
Latest commit contain a fix for this, https://github.com/lendy007/skodaconnect/pull/30

**Comment by Farfar** [comment]
Fixed in commit 40363714f179b61ff67afeb462e798ff6e44cd24, will be included in release 1.1.0 when released.
