### ISSUE TITLE
No Function anymore with Skoda Citigo-eIV

### ISSUE THREAD

**Issue by hhoefling** [lendy007/skodaconnect#36]
Version 1.42 are the last Version that works with my Citigo
Bad news for me ...
Seems to work only with Enyaq

**Comment by hhoefling** [comment]
1.0.52 works in parts
1.10 does not work ( 404'e Error in logfile)

**Comment by Farfar** [comment]
> Version 1.42 are the last Version that works with my Citigo

Does nothing work? Same account as the Enyaq?

> 1.10 does not work ( 404'e Error in logfile)

1.10 isn't ready quite yet but it should be working.
Could you share your log files, or perhaps join the Discord?

**Comment by Farfar** [comment]
> > Version 1.42 are the last Version that works with my Citigo
> 
> Does nothing work? Same account as the Enyaq?
> 
> > 1.10 does not work ( 404'e Error in logfile)
> 
> 1.10 isn't ready quite yet but it should be working.
> Could you share your log files, or perhaps join the Discord?

Can you try removing the comment on line 29 of skodaconnect/const.py and then commenting out line 30?
So instead of:
```
#XCLIENT_ID = '28cd30c6-dee7-4529-a0e6-b1e07ff90b79'
XCLIENT_ID = 'a83d7e44-c8b7-42b7-b8ca-e478270d2091'
```
You have:
```
XCLIENT_ID = '28cd30c6-dee7-4529-a0e6-b1e07ff90b79'
#XCLIENT_ID = 'a83d7e44-c8b7-42b7-b8ca-e478270d2091'
```

**Comment by Farfar** [comment]
Fixed in latest commit. Scheduled for 1.1.1 release.

**Comment by hhoefling** [comment]
> XCLIENT_ID = '28cd30c6-dee7-4529-a0e6-b1e07ff90b79'
> #XCLIENT_ID = 'a83d7e44-c8b7-42b7-b8ca-e478270d2091'

This make no difference, Same Error,
(and same Logfile,  only Currend-Date/Times are different.)

**Comment by Farfar** [comment]
> > XCLIENT_ID = '28cd30c6-dee7-4529-a0e6-b1e07ff90b79'
> > #XCLIENT_ID = 'a83d7e44-c8b7-42b7-b8ca-e478270d2091'
> 
> This make no difference, Same Error,
> (and same Logfile, only Currend-Date/Times are different.)
> 
> I will try 1.1.x

Good. Were a few bugs found immediately after releases were out so 1.1.3 is the current version to try.

**Comment by hhoefling** [comment]
1.1.3 works.
First Tests (read Car State) are Ok.
