### ISSUE TITLE
pheater "off" and honkandflash error

### ISSUE THREAD

**Issue by jfmennedy** [lendy007/skodaconnect#38]
Switching pheater off `vehicle.set_pheater(mode="off", spin="1234")` results in error: 
`ERROR    - skodaconnect.connection: Unhandled HTTP exception: 403, message='Forbidden', url=URL('https://msg.volkswagen.de/fs-car/bs/rs/v1/skoda/CZ/vehicles/Tasdfasdfasasdfasdfasdfasf3/action')`

heating or ventilation on are ok, only off does not work.

Switching honkandflash `vehicle.set_honkandflash(action = "flash")` results in error: 
`WARNING:skodaconnect.vehicle:Failed to flash vehicle - name 'latitude' is not defined`

**Comment by Farfar** [comment]
Thanks for the report, will look into this.

**Comment by Farfar** [comment]
@jfmennedy  Could you try pheater off again? I can't see anything that might cause a problem and it should work equally well as heating/ventilation, there's no difference in the service call now and previous versions as far as I can tell.

**Comment by jfmennedy** [comment]
Tried again, thats the error:
`Traceback (most recent call last):
  File "C:/Users/testing/PycharmProjects/skodaconnect-1.1.3/example/example.py", line 305, in <module>
    loop.run_until_complete(main())
  File "C:\Users\testing\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "C:/Users/Jan Menninger/PycharmProjects/skodaconnect-1.1.3/example/example.py", line 290, in main
    if await vehicle.set_pheater(mode="off", spin="2312"):
  File "C:\Users\testing\PycharmProjects\skodaconnect-1.1.3\skodaconnect\vehicle.py", line 897, in set_pheater
    response = await self._connection.setPreHeater(self.vin, data, spin)
  File "C:\Users\testing\PycharmProjects\skodaconnect-1.1.3\skodaconnect\connection.py", line 1364, in setPreHeater
    response = await self._setVWAPI(f'fs-car/bs/rs/v1/{BRAND}/{COUNTRY}/vehicles/{vin}/action', json = data)
  File "C:\Users\Jan Menninger\PycharmProjects\skodaconnect-1.1.3\skodaconnect\connection.py", line 1185, in _setVWAPI
    raise SkodaException(f'Invalid or no response for endpoint {endpoint}')
skodaconnect.exceptions.SkodaException: Invalid or no response for endpoint fs-car/bs/rs/v1/skoda/CZ/vehicles/Tyxcvyxcvyxcvxcv73/action` 

It worked in earlier versions, thats why i am wondering, why it is not working anymore. perhaps the commd for off changed besides skoda?

**Comment by Farfar** [comment]
> `(most recent call last): File "C:/Users/testing/PycharmProjects/skodaconnect-1.1.3/example/example.py", line 305, in <module> loop.run_until_complete(main()) File "C:\Users\testing\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 616, in run_until_complete return future.result() File "C:/Users/testing/PycharmProjects/skodaconnect-1.1.3/example/example.py", line 290, in main if await vehicle.set_pheater(mode="off", spin="2312"): File "C:\Users\testing\PycharmProjects\skodaconnect-1.1.3\skodaconnect\vehicle.py", line 897, in set_pheater response = await self._connection.setPreHeater(self.vin, data, spin) File "C:\Users\testing\PycharmProjects\skodaconnect-1.1.3\skodaconnect\connection.py", line 1364, in setPreHeater response = await self._setVWAPI(f'fs-car/bs/rs/v1/{BRAND}/{COUNTRY}/vehicles/{vin}/action', json = data) File "C:\Users\testing\PycharmProjects\skodaconnect-1.1.3\skodaconnect\connection.py", line 1185, in _setVWAPI raise SkodaException(f'Invalid or no response for endpoint {endpoint}') skodaconnect.exceptions.SkodaException: Invalid or no response for endpoint fs-car/bs/rs/v1/skoda/CZ/vehicles/Tyxcvyxcvyxcvxcv73/action`

Do you remember the last working version?

**Comment by jfmennedy** [comment]
i am shure it has been working un 1.0.40. if it has been working in 1.0.42 i do not know

**Comment by Farfar** [comment]
> i am shure it has been working un 1.0.40. if it has been working in 1.0.42 i do not know

I think I know now why it doesn't work. It looks as if it always tries to fetch security token even if the action is stop. The code logic as it is implemented does not work. However, this should have been the issue with earlier versions as well since the logic hasn't changed.
If you use the correct S-PIN, does the request work then?

**Comment by jfmennedy** [comment]
S-Pin is used for each pheater command.

**Comment by Farfar** [comment]
> S-Pin is used for each pheater command.

Yes I know. But are you using the correct S-PIN for your vehicle?
Either way, there's a new version that I hope will fix this issue. Please try it out and see if there's any difference.

**Comment by jfmennedy** [comment]
switching off in 1.1.4 fixed. need to test honk and flash, but not at the car at the moment.. will give feedback later this day

**Comment by jfmennedy** [comment]
nice, honkandflash is working 🥇
