### ISSUE TITLE
My car is not listed

### ISSUE THREAD

**Issue by flopp999** [lendy007/skodaconnect#40]
Today there was an update or error with Skoda server.
My car didn't show up in Skoda app.
Now I can see my car again in Skoda app, but with Skodaconnect my car is not listed.
Debian 10, python 3.7.3, PyJWT 2.1.0

![image](https://user-images.githubusercontent.com/21694965/133263015-6d3a9fe0-7115-4100-8760-737bddbbf857.png)

**Comment by jpalo** [comment]
There seems to be some issue with the service. I'm getting login failed 504 errors.

```
########################################
#      Logging on to Skoda Connect     #
########################################
Initiating new session to Skoda Connect with xx@xx.com as username
INFO:skodaconnect.connection:Init Skoda Connect library, version 1.1.6
DEBUG:skodaconnect.connection:Using service https://msg.volkswagen.de
Attempting to login to the Skoda Connect service
2021-09-14 16:34:33.452433
INFO:skodaconnect.connection:Initiating new login
DEBUG:skodaconnect.connection:Starting authorization process for client skoda
DEBUG:skodaconnect.connection:Got redirect to signin-service
DEBUG:skodaconnect.connection:Start authorization for user xx@xx.com
DEBUG:skodaconnect.connection:Finalizing login
DEBUG:skodaconnect.connection:Received authorization code, exchange for tokens.
ERROR:skodaconnect.connection:Login failed for xx@xx.com, API returned HTTP status 504
```

**Comment by Farfar** [comment]
504 is indication of server-side problem. I would give it a few days and try again.

**Comment by flopp999** [comment]
My Skoda app works now but Skodaconnect still doesn't list my car.

Anything you already know?

No error, it says login successful.

**Comment by Farfar** [comment]
> My Skoda app works now but Skodaconnect still doesn't list my car.
> 
> Anything you already know?
> 
> No error, it says login successful.

No everything is working fine here now. 
Depending on which car you have there's up to 2 logins made and up to 3(4) different tokens fetched. Check the logs and make sure that one of them doesn't fail ('connect', 'skoda' and 'vwg').
One user reported that all started working for him after he changed password in Skoda Connect portal.

**Comment by flopp999** [comment]
My mistake. It seems that I had changed something in my example file.
With you example file it worked fine.
Sorry :)
