### ISSUE TITLE
Syntax error v1.1.10

### ISSUE THREAD

**Issue by romanmatyus** [lendy007/skodaconnect#44]
Hello, I receive error when I try run example from github on ubuntu.

Do you have any idea where is problem?

Thanks

```bash
$ ./example.py 
Traceback (most recent call last):
  File "./example.py", line 17, in <module>
    from skodaconnect import Connection
  File "skodaconnect/skodaconnect/__init__.py", line 7, in <module>
    from skodaconnect.connection import Connection
  File "<fstring>", line 1
    (await req.text())
             ^
SyntaxError: invalid syntax
```

```bash
$ python3 --version
Python 3.6.9
```

**Comment by WebSpider** [comment]
Offending line is https://github.com/lendy007/skodaconnect/blob/afc7924f727b85069f0b15611f154980e82214b7/skodaconnect/connection.py#L238

I am running this code on ubuntu 20.04 without any issue on python 3.8.10, probably is version specific.
