### ISSUE TITLE
odometer, position and speed

### ISSUE THREAD

**Issue by mrubioroy** [lendy007/skodaconnect#47]
Hi, any chance we can get odometer, position and speed readings for Skoda cars?
I see VW Car-Net can be used in this way for odometer and position:
https://github.com/thomasesmith/vw-car-net-api#now-you-can-get-a-vehicles-status-summary
and
https://github.com/thomasesmith/vw-car-net-api#retrieving-vehicle-health-report-data

I haven't found any API endpoint for speed.

**Comment by Farfar** [comment]
> Hi, any chance we can get odometer, position and speed readings for Skoda cars? I see VW Car-Net can be used in this way for odometer and position: https://github.com/thomasesmith/vw-car-net-api#now-you-can-get-a-vehicles-status-summary and https://github.com/thomasesmith/vw-car-net-api#retrieving-vehicle-health-report-data
> 
> I haven't found any API endpoint for speed.

There is no endpoint for speed and odometer+position is already in this library.
Since you are asking I suspect that you have an Enyaq and odometer+position is not yet available for Enyaq.
