### ISSUE TITLE
Skoda Enyaq change max current

### ISSUE THREAD

**Issue by flopp999** [lendy007/skodaconnect#48]
Hi, very nice script you have done :)

I tried to use your set-command and found that when I set_charger_current to Reduced it also change the charge limit to 100%.

Is this correct and why?

https://github.com/lendy007/skodaconnect/blob/b98b39747e6940b5948127b010dcbb6d5230437d/skodaconnect/vehicle.py#L369

**Comment by Farfar** [comment]
> Hi, very nice script you have done :)
> 
> I tried to use your set-command and found that when I set_charger_current to Reduced it also change the charge limit to 100%.
> 
> Is this correct and why?
> 
> https://github.com/lendy007/skodaconnect/blob/b98b39747e6940b5948127b010dcbb6d5230437d/skodaconnect/vehicle.py#L369

No this is not correct behaviour, I will look into it for next release. Thanks for bringing it to my attention.

**Comment by Farfar** [comment]
This should be solved in latest release

**Comment by flopp999** [comment]
Thanks. Tried it now in version 1.1.12 and it works correct now.
