### ISSUE TITLE
No vehicle found

### ISSUE THREAD

**Issue by bergerw** [lendy007/skodaconnect#49]
Hi

I would like to use your script. But what I try I get an error about no vehicle. On the MySkoda App I see my Enyaq
Any Idea what could be wrong?

Log:
########################################
#      Logging on to Skoda Connect     #
########################################
Initiating new session to Skoda Connect with werner.berger@bluewin.ch as username
INFO:skodaconnect.connection:Init Skoda Connect library, version 1.1.11
DEBUG:skodaconnect.connection:Using service https://msg.volkswagen.de
Attempting to login to the Skoda Connect service
2021-11-05 11:11:15.081136
INFO:skodaconnect.connection:Initiating new login
DEBUG:skodaconnect.connection:Starting authorization process for client skoda
DEBUG:skodaconnect.connection:Got redirect to signin-service
DEBUG:skodaconnect.connection:Start authorization for user werner.berger@bluewin.ch
DEBUG:skodaconnect.connection:Finalizing login
DEBUG:skodaconnect.connection:Received authorization code, exchange for tokens.
DEBUG:skodaconnect.connection:Verifying token for f9a2359a-b776-46d9-bd0c-db1904343117@apps_vw-dilab_com
DEBUG:skodaconnect.connection:Token for skoda verified OK.
Login success!
2021-11-05 11:11:16.890504
Fetching vehicles associated with account.
DEBUG:skodaconnect.connection:Client "connect" token is missing, call to authorize the client.
DEBUG:skodaconnect.connection:Starting authorization process for client connect
DEBUG:skodaconnect.connection:Received authorization code, exchange for tokens.
DEBUG:skodaconnect.connection:Verifying token for 7f045eee-7003-4379-9968-9355ed2adb06@apps_vw-dilab_com
DEBUG:skodaconnect.connection:Token for connect verified OK.
DEBUG:skodaconnect.connection:Request for "https://profileintegrityservice.apps.emea.vwapps.io/iaa/pic/v1/users/146229d6-e583-429f-9624-980185a7269b/check-profile" returned with status code [200]
DEBUG:skodaconnect.connection:Consent returned {'consentInfo': {'scopeId': 'commonMandatoryFields', 'ssoId': '146229d6-e583-429f-9624-980185a7269b', 'missingMandatoryFields': [], 'mbbUserId': '0TuRRJZZAXFR5dYwbdlWNmR4AQG', 'mbbIdStatus': True, 'mandatoryFieldsStatus': True, 'spinStatus': True, 'mandatoryConsentInfo': [{'id': 'termsOfUse', 'status': 'VALID'}]}}
DEBUG:skodaconnect.connection:User consent is valid, no missing information for profile
DEBUG:skodaconnect.connection:Got non HTTP related error: Cannot connect to host api.connect.skoda-auto.cz:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1108)')]
DEBUG:skodaconnect.connection:Skoda native API returned no vehicles. Using fallback VW-Group API.
DEBUG:skodaconnect.connection:Client "vwg" token is missing, call to authorize the client.
DEBUG:skodaconnect.connection:Trying to fetch api tokens.
DEBUG:skodaconnect.connection:Verifying token for mal.prd.ece.vwg-connect.com
DEBUG:skodaconnect.connection:VW-Group API token verified OK.
DEBUG:skodaconnect.connection:Request for "https://msg.volkswagen.de/fs-car/usermanagement/users/v1/skoda/CZ/vehicles" returned with status code [200]
Traceback (most recent call last):
  File "example.py", line 289, in <module>
    loop.run_until_complete(main())
  File "C:\Program Files\Python38\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "example.py", line 130, in main
    await connection.get_vehicles()
  File "C:\Users\Werner\Downloads\skodaconnect-1.1.11\skodaconnect-1.1.11\skodaconnect\connection.py", line 690, in get_vehicles
    if response.get('userVehicles', {}).get('vehicle', False):
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by Farfar** [comment]
> DEBUG:skodaconnect.connection:Got non HTTP related error: Cannot connect to host api.connect.skoda-auto.cz:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1108)')]

This is the issue, your computer can't connect because of expired certificate om API server.
Not sure if there's actually incorrect certificate sent from server or if your computer have problems in trust store.

**Comment by bergerw** [comment]
Could solve the problem with 

1. Download https://letsencrypt.org/certs/lets-encrypt-r3.pem 189
2. rename file .pem to .cer
3. double click and install

It seem that for some reason the certificate "ISRG Root X1" was not installed in the right way on my windows 10 computer.
