### ISSUE TITLE
my own code giving "Failed to authorize client skoda"

### ISSUE THREAD

**Issue by flopp999** [lendy007/skodaconnect#50]
I am using your code inside my own code for Domoticz.

When I start Domoticz I get this error, if I restart my code it start to work. So my code is working and I am trying to find a way to solve the error.

Do you know a command that I can use with your code to restart the get_vehicles?

Thanks

```
Traceback (most recent call last):
File "/home/debian/domoticz/plugins/Skoda/plugin.py", line 70, in main
await connection.get_vehicles()
File "/usr/local/lib/python3.9/dist-packages/skodaconnect/connection.py", line 670, in get_vehicles
await self.set_token('skoda')
File "/usr/local/lib/python3.9/dist-packages/skodaconnect/connection.py", line 1666, in set_token
raise SkodaAuthenticationException(f'Failed to authorize client {client}')
skodaconnect.exceptions.SkodaAuthenticationException: Failed to authorize client skoda
<class 'skodaconnect.exceptions.SkodaAuthenticationException'>
```

**Comment by Farfar** [comment]
> I am using your code inside my own code for Domoticz.
> 
> When I start Domoticz I get this error, if I restart my code it start to work. So my code is working and I am trying to find a way to solve the error.
> 
> Do you know a command that I can use with your code to restart the get_vehicles?
> 
> Thanks
> 
> ```
> Traceback (most recent call last):
> File "/home/debian/domoticz/plugins/Skoda/plugin.py", line 70, in main
> await connection.get_vehicles()
> File "/usr/local/lib/python3.9/dist-packages/skodaconnect/connection.py", line 670, in get_vehicles
> await self.set_token('skoda')
> File "/usr/local/lib/python3.9/dist-packages/skodaconnect/connection.py", line 1666, in set_token
> raise SkodaAuthenticationException(f'Failed to authorize client {client}')
> skodaconnect.exceptions.SkodaAuthenticationException: Failed to authorize client skoda
> <class 'skodaconnect.exceptions.SkodaAuthenticationException'>
> ```

You can call the method connection.get_vehicles() directly. Or have I misunderstood you?
It might help if you paste relevant code snippet from your code.

**Comment by flopp999** [comment]
Thanks for quick reply.
Please see link below
https://github.com/flopp999/SkodaConnect-Domoticz/blob/36c5aa4aa0c241e65a5b7d3cd86f059fd70be6f4/plugin.py#L70

**Comment by Farfar** [comment]
> Thanks for quick reply. Please see link below https://github.com/flopp999/SkodaConnect-Domoticz/blob/36c5aa4aa0c241e65a5b7d3cd86f059fd70be6f4/plugin.py#L70

I would, on line 70, add some error handling. The get_vehicles method should return a dict with the vehicle information. If something goes wrong it will error out. So a "simple" try: except: clause would solve it. Perhaps add a loop or something to loop with a set delay until it succeeds.

**Comment by Farfar** [comment]
Closed this issue since it isn't related to the library.
