### ISSUE TITLE
Window-Heater not working for Skoda Enyaq

### ISSUE THREAD

**Issue by scoutice** [lendy007/skodaconnect#61]
hi there. i think t the dection of the window-heater for the skoda enyaq. does not work. here i have an examle of the full debug-log:

here it is off (this is correct)

`
DEBUG:skodaconnect.connection:Request for "https://api.connect.skoda-auto.cz/api/v1/air-conditioning/<VIN>/settings" returned with status code [200]
DEBUG:skodaconnect.connection:Request for "https://api.connect.skoda-auto.cz/api/v1/air-conditioning/<VIN>/status" returned with status code [200]
INFO:skodaconnect.connection:Returning with data {'airConditioning': {'remainingTimeToReachTargetTemperatureInSeconds': 0, 'state': 'Off', 'trigger': 'OFF', 'windowsHeatingStatuses': [{'windowLocation': 'Front', 'state': 'Off'}, {'windowLocation': 'Rear', 'state': 'Off'}], 'seatHeatingSupport': {'frontLeftAvailable': True, 'frontRightAvailable': True, 'rearLeftAvailable': False, 'rearRightAvailable': False}}, 'airConditioningSettings': {'targetTemperatureInKelvin': 295.15, 'temperatureConversionTableUsed': 'CELSIUS_KELVIN', 'airConditioningAtUnlock': False, 'windowHeatingEnabled': True, 'zonesSettings': {'frontLeftEnabled': True, 'frontRightEnabled': False}}}
but here it was turned on before:
DEBUG:skodaconnect.connection:Request for "https://api.connect.skoda-auto.cz/api/v1/air-conditioning/<VIN>/settings" returned with status code [200]
DEBUG:skodaconnect.connection:Request for "https://api.connect.skoda-auto.cz/api/v1/air-conditioning/<VIN>/status" returned with status code [200]
INFO:skodaconnect.connection:Returning with data {'airConditioning': {'remainingTimeToReachTargetTemperatureInSeconds': 0, 'state': 'Off', 'trigger': 'OFF', 'windowsHeatingStatuses': [{'windowLocation': 'Front', 'state': 'On'}, {'windowLocation': 'Rear', 'state': 'On'}], 'seatHeatingSupport': {'frontLeftAvailable': True, 'frontRightAvailable': True, 'rearLeftAvailable': False, 'rearRightAvailable': False}}, 'airConditioningSettings': {'targetTemperatureInKelvin': 295.15, 'temperatureConversionTableUsed': 'CELSIUS_KELVIN', 'airConditioningAtUnlock': False, 'windowHeatingEnabled': True, 'zonesSettings': {'frontLeftEnabled': True, 'frontRightEnabled': False}}}`
as you can see, the window-front-state is "on".

however, in both cases the vehicle dasboard says "off"
`<VIN>Window Heater - (window_heater)
        str_state: Off - state: False
        attributes: {'last_result': 'None', 'last_timestamp': '1970-01-01T00:00:00'}`
did I miss something? i have not tried yet to set it using the API, but this would be the next step (as my python is very bad, i always test it reading first)

**Comment by scoutice** [comment]
I'm currently working on a path, but must find out first how to use github-patches. 

in dashboard.py and vehicle.py i changed and added some simple lines
[skodaconnect.zip](https://github.com/lendy007/skodaconnect/files/10050633/skodaconnect.zip)
but i will test them and probably do a merge-request...

**Comment by Farfar** [comment]
Thanks for your contribution! I will release new version with fix included ASAP.

**Comment by Farfar** [comment]
Fixed in 1.0.27
