### ISSUE TITLE
Example raises DeprecationWarning on __main__

### ISSUE THREAD

**Issue by scoutice** [lendy007/skodaconnect#65]
example.py:316: DeprecationWarning: There is no current event loop

As stated in https://www.reddit.com/r/learnpython/comments/smb2dt/aiohttp_error_deprecationwarning_there_is_no/

shall be replaced through
 `   asyncio.run(main())`
or (i think even better)
```
    loop = asyncio.new_event_loop()
    loop.run_until_complete(main())

```

**Comment by Farfar** [comment]
Thanks! Will be included in 1.3.1 release I'm currently testing.
