### ISSUE TITLE
after using example.py once - some data in the app got deleted

### ISSUE THREAD

**Issue by gitunit** [lendy007/skodaconnect#67]
i used the example.py once and was successfully able to login and get info.
later i checked the app on my mobile refreshed the main screen and it showed an error saying "car deleted", clicking ok most information was still there but the dealer setting was gone. 
do you know what could be the reason for this?

**Comment by Farfar** [comment]
> i used the example.py once and was successfully able to login and get info. later i checked the app on my mobile refreshed the main screen and it showed an error saying "car deleted", clicking ok most information was still there but the dealer setting was gone. do you know what could be the reason for this?

I don't use the app that often but I noticed that my service partner was cleared as well. I have no idea why, could be related to recent changes on VW's servers since there's nothing in the library code that can set service info.
