### ISSUE TITLE
Login failed with latest v1.2.3 release

### ISSUE THREAD

**Issue by jvuotila** [lendy007/skodaconnect#68]
Login failed. Error messages below.

Integration -> Retrying setup: 'NoneType' object has no attribute 'get'
Log -> Config entry 'xxxxxxxxxxxxxxxxx' for skodaconnect integration not ready yet: 'NoneType' object has no attribute 'get'; Retrying in background

**Comment by Farfar** [comment]
> Login failed. Error messages below.
> 
> Integration -> Retrying setup: 'NoneType' object has no attribute 'get' Log -> Config entry 'xxxxxxxxxxxxxxxxx' for skodaconnect integration not ready yet: 'NoneType' object has no attribute 'get'; Retrying in background

Check the countless open/closed issues before you open a new one. This issue is because of new consent required. Login to your app and check, which should always be first step in troubleshooting when something isn't working.

**Comment by Farfar** [comment]
And I just realised that all issues are opened against the other repo so it's not something you could have known, sorry.
