### ISSUE TITLE
No data due to "deactivation"?

### ISSUE THREAD

**Issue by anemac1** [lendy007/skodaconnect#9]
Hi,
i'm using the latest commit of skodaconnect and importing farfar/seatconnect to connect to my Mii electric BEV. Although the code is running I do not get any data (except for the static data VIN, Model, etc.). 
Logging shows me this:

> DEBUG:seatconnect.connection:Going to call vehicle updates
> INFO:seatconnect.vehicle:Vehicle with VIN VSSZZZAAXXX123456 is deactivated from Seat Connect

but I cant figure out what that means. Data in my iPhone Seat Connect app and on the web is available and gets updated.
Its not a number of requests issue as this is shown even if I do not any data updates for a whole day. Any clues? 
BR, A

**Comment by Farfar** [comment]
> Hi,
> i'm using the latest commit of skodaconnect and importing farfar/seatconnect to connect to my Mii electric BEV. Although the code is running I do not get any data (except for the static data VIN, Model, etc.).
> Logging shows me this:
> 
> > DEBUG:seatconnect.connection:Going to call vehicle updates
> > INFO:seatconnect.vehicle:Vehicle with VIN VSSZZZAAXXX123456 is deactivated from Seat Connect
> 
> but I cant figure out what that means. Data in my iPhone Seat Connect app and on the web is available and gets updated.
> Its not a number of requests issue as this is shown even if I do not any data updates for a whole day. Any clues?
> BR, A

Can you enable full debug and paste raw response for the operationlist? It seems it thinks your car doesn't have a valid Connect license.

**Comment by anemac1** [comment]
Hi,
just a few hours ago I tried again the same code and now it seems to work, the info does not appear anymore although nothing was changed (at least from my side).
I now slightly changed the example so only the battery level and a timestamp are printed.

In my log ([output - Kopie.log](https://github.com/lendy007/skodaconnect/files/6054483/output.-.Kopie.log))
 still some warnings appear and I would be grateful to get explained what might be the problems here:
- When looking at my log now the error jwt.algorithms appears, even though I downgraded pyjwt to 1.7.1. Although the WARNING says "Token could not be verified!" the next line shows "Successfully refreshed tokens"?
- after having done a few loops there is no new loop output printed although it seems that update requests are made and the current status is retrieved properly. But the only information shown are the connection requests in the log. What might be the problem here?

Thx so much in advance and
Br, A

**Comment by Farfar** [comment]
> Hi,
> just a few hours ago I tried again the same code and now it seems to work, the info does not appear anymore although nothing was changed (at least from my side).
> I now slightly changed the example so only the battery level and a timestamp are printed.
> 
> In my log ([output - Kopie.log](https://github.com/lendy007/skodaconnect/files/6054483/output.-.Kopie.log))
> still some warnings appear and I would be grateful to get explained what might be the problems here:
> 
> * When looking at my log now the error jwt.algorithms appears, even though I downgraded pyjwt to 1.7.1. Although the WARNING says "Token could not be verified!" the next line shows "Successfully refreshed tokens"?
> * after having done a few loops there is no new loop output printed although it seems that update requests are made and the current status is retrieved properly. But the only information shown are the connection requests in the log. What might be the problem here?
> 
> Thx so much in advance and
> Br, A

Ok, then it was probably temporary server side problems.
If the token can't be verified it just medans that there's a new issuer of tokens I haven't seen yet, there's already some trickery in code to make tokens validate correctly but something might have changed. This is just a security measure though and won't affect functionality.

Why the information doesn't show I do not know, the example code is just that. An example. I have never tried it, and it's not meant to, rum forever. It's just meant to showcase methods.
